export const regionOptions = [
  { value: "01", label: "Provinsi Aceh" },
  { value: "02", label: "Provinsi Sumatera Utara" },
  { value: "03", label: "Provinsi Sumatera Barat" },
  { value: "04", label: "Provinsi Riau" },
  { value: "05", label: "Provinsi Jambi" },
  { value: "06", label: "Provinsi Sumatera Selatan" },
  { value: "07", label: "Provinsi Bengkulu" },
  { value: "08", label: "Provinsi Lampung" },
  { value: "09", label: "Provinsi DKI Jakarta" },
  { value: "10", label: "Provinsi Jawa Barat" },
  { value: "11", label: "Provinsi Jawa Tengah" },
  { value: "12", label: "Provinsi DI Yogyakarta" },
  { value: "13", label: "Provinsi Jawa Timur" },
  { value: "14", label: "Provinsi Kalimantan Barat" },
  { value: "15", label: "Provinsi Kalimantan Tengah" },
  { value: "16", label: "Provinsi Kalimantan Selatan" },
  { value: "17", label: "Provinsi Kalimantan Timur" },
  { value: "18", label: "Provinsi Sulawesi Utara" },
  { value: "19", label: "Provinsi Sulawesi Tengah" },
  { value: "20", label: "Provinsi Sulawesi Selatan" },
  { value: "21", label: "Provinsi Sulawesi Tenggara" },
  { value: "22", label: "Provinsi Bali" },
  { value: "23", label: "Provinsi Nusa Tenggara Barat" },
  { value: "24", label: "Provinsi Nusa Tenggara Timur" },
  { value: "25", label: "Provinsi Maluku" },
  { value: "26", label: "Provinsi Papua" },
  { value: "27", label: "Provinsi Maluku Utara" },
  { value: "28", label: "Provinsi Banten" },
  { value: "29", label: "Provinsi Bangka Belitung" },
  { value: "30", label: "Provinsi Gorontalo" },
  { value: "31", label: "Provinsi Kepulauan Riau" },
  { value: "32", label: "Provinsi Papua Barat" },
  { value: "33", label: "Provinsi Sulawesi Barat" },
  { value: "34", label: "Provinsi Kalimantan Utara" },
  { value: "35", label: "Provinsi Papua Selatan" },
  { value: "36", label: "Provinsi Papua Tengah" },
  { value: "37", label: "Provinsi Papua Pegunungan" },
  { value: "38", label: "Provinsi Papua Barat Daya" },
];